### ISSUE TITLE
pip install -r requirements.txt

### ISSUE THREAD

**Issue by mapanare** [maxsteel1947/CryptoBox-AutoScript#1]
requirements.txt   

 not found

**Comment by Nandrei11** [comment]
also interested

**Comment by vijju1996** [comment]
wht are requirement for it

**Comment by maxsteel1947** [comment]
All the requirements are included in the code.

just add a .env file with your Telegram login credentials.

**Comment by vijju1996** [comment]
.env file is not available in it

**Comment by maxsteel1947** [comment]
you have to create a .env file which is simple.

Doesn't matter Binance has updated the UI for crypto box page. The code
needs to be updated with the new page elements.

**Comment by dony971** [comment]
please help us

**Comment by maxsteel1947** [comment]
Hello Dony,

I am not a dev, but I will help however I can,
the code will not work since the binance webpage is changed and the
selenium needs to be reconfigured which is a very time consuming and hectic
task.
you can reach me at ***@***.***

Let me know what you need from me.
