### ISSUE TITLE
Security Verification Requirements

### ISSUE THREAD

**Issue by mapanare** [maxsteel1947/CryptoBox-AutoScript#2]
Security Verification Requirements
You need to complete all of the following verifications to continue.

02 step

Email
Phone Number

**Comment by maxsteel1947** [comment]
Run a chrome instance in developer mode. Ensure the port to interact with chrome dev instance is open and running.

You can check it with chrome://inspect and see if the https://www.binance.com/en/my/wallet/account/payment/cryptobox Page is running in chrome dev instance. also as per latest update Binance has changed its UI which may require to update this repo.
Remote Target
#LOCALHOST

once done its should work fine and copy the codes from telegram chat and paste and claim on binance pay page.
